#!/usr/bin/env python

import dircache
import drplot
import numpy
import pylab

HOSTS = {"gemini": 0, "molly": 1, "orion": 2, "dev": 3, "ferb": 4}

starttime = []
hostname = []
jobtime = []
rebintime = []
rebinvol = []
rebinthp = []
recordedcnts = []
nonemptybins = []
inputpix = []
realtime = []
usertime = []
systime = []

def get_col_val(istr, **kwargs):
    units = kwargs.get('units', False)
    thp = kwargs.get('thp', False)
    percent = kwargs.get('percent', False)
    stime = kwargs.get('stime', False)
    volume = kwargs.get('volume', False)

    parts = istr.split(':')
    
    if units:
        return parts[-1].split()[0].strip()

    if thp:
        return parts[-1].split()[3].strip()

    if percent:
        return parts[-1].split()[0].strip().strip('%')

    if stime:
        min = float(istr.split()[-1].split('m')[0])
        sec = float(istr.split()[-1].split('m')[1].rstrip('s'))
        return sec + (min * 60.0)

    if volume:
        size = 1
        for x in parts[-1].split():
            size *= int(x)
        return size

    return parts[-1].strip()

for ifile in dircache.listdir('.'):
    if not ifile.endswith('.out'):
        continue

    ifileh = open(ifile, 'r')
    ilines = ifileh.readlines()
    ifileh.close()

    for iline in ilines:
        if "Start" in iline:
            starttime.append(int(get_col_val(iline)))
        elif "Hostname" in iline:
            hname = get_col_val(iline)
            hostname.append(HOSTS[hname])
        elif "Job Time" in iline:
            jobtime.append(int(get_col_val(iline)))
        elif "real" in iline:
            realtime.append(get_col_val(iline, stime=True))
        elif "user" in iline:
            usertime.append(get_col_val(iline, stime=True))
        elif "sys" in iline:
            systime.append(get_col_val(iline, stime=True))
        elif "rebin throughput" in iline:
            rebinthp.append(float(get_col_val(iline, units=True)))
        elif "num_pixels processed" in iline:
            inputpix.append(int(get_col_val(iline)))
        elif "recorded total cnt" in iline:
            recordedcnts.append(float(get_col_val(iline)))
        elif "nonempty bins" in iline:
            nonemptybins.append(int(get_col_val(iline)))
        elif "volume size" in iline:
            rebinvol.append(get_col_val(iline, volume=True))

# Get the fraction of the rebinned volume that is occupied
rebinvolnp = numpy.array(rebinvol, dtype=numpy.float64)
nonemptybinsnp = numpy.array(nonemptybins, dtype=numpy.float64)
rebinfrac = nonemptybinsnp / rebinvolnp * 100.0

starttimenp = numpy.array(starttime)
jobtimenp = numpy.array(jobtime)
totaltime = starttime + jobtime
mintime = numpy.min(starttimenp)
maxtime = numpy.max(totaltime)
print "Total Run Time:", maxtime - mintime, "seconds"
            
xaxis = numpy.arange(len(starttime))

f1 = pylab.figure(1)
pylab.subplot(3,5,1)
drplot.plot_1D_arr(xaxis, numpy.array(jobtime), xlabel="Slice ID",
                   ylabel="Job Time (sec)")
pylab.subplot(3,5,2)
drplot.plot_1D_arr(xaxis, numpy.array(starttime), xlabel="Slice ID",
                   ylabel="Start Time (Unix sec)")
pylab.subplot(3,5,3)
drplot.plot_1D_arr(xaxis, numpy.array(rebinthp), xlabel="Slice ID",
                   ylabel="Rebin Throughput (pix/sec)")
pylab.subplot(3,5,4)
drplot.plot_1D_arr(xaxis, rebinfrac, xlabel="Slice ID",
                   ylabel="Rebin Volume (% occ)")
pylab.subplot(3,5,5)
drplot.plot_1D_arr(xaxis, numpy.array(recordedcnts), xlabel="Slice ID",
                   ylabel="Recorded Total Counts")
pylab.subplot(3,5,6)
drplot.plot_1D_arr(xaxis, numpy.array(inputpix), xlabel="Slice ID",
                   ylabel="Input Pixels")
pylab.subplot(3,5,7)
drplot.plot_1D_arr(xaxis, numpy.array(realtime), xlabel="Slice ID",
                   ylabel="Real Time (sec)")
pylab.subplot(3,5,8)
drplot.plot_1D_arr(xaxis, numpy.array(usertime), xlabel="Slice ID",
                   ylabel="User Time (sec)")
pylab.subplot(3,5,9)
drplot.plot_1D_arr(xaxis, numpy.array(systime), xlabel="Slice ID",
                   ylabel="Sys Time (sec)")
pylab.subplot(3,5,10)
drplot.plot_1D_arr(xaxis, numpy.array(nonemptybins), xlabel="Slice ID",
                   ylabel="Non-Empty Bins")
pylab.subplot(3,5,11)
drplot.plot_1D_arr(numpy.array(jobtime), numpy.array(recordedcnts),
                   xlabel="Job Time (sec)", ylabel="Recorded Total Counts")
pylab.subplot(3,5,12)
drplot.plot_1D_arr(numpy.array(jobtime), numpy.array(rebinthp),
                   xlabel="Job Time (sec)",
                   ylabel="Rebin Throughput (pix/sec)")
pylab.subplot(3,5,13)
drplot.plot_1D_arr(numpy.array(jobtime), rebinfrac,
                   xlabel="Job Time (sec)",
                   ylabel="Rebin Volume (% occ)")
pylab.subplot(3,5,14)
drplot.plot_1D_arr(numpy.array(rebinthp), rebinfrac,
                   xlabel="Rebin Throughput (pix/sec)",
                   ylabel="Rebin Volume (% occ)")
pylab.subplot(3,5,15)
drplot.plot_1D_arr(numpy.array(hostname), numpy.array(jobtime), xlabel="Host",
                   ylabel="Job Time (sec)")
pylab.show()
